---
version: '3'

services:
  crypticcoind:
    build: .
    env_file:
      - .env
    volumes:
      - ./crypticcoin-params-dir:/srv/crypticcoind/.crypticcoin-params
      - ./crypticcoin-data-dir:/srv/crypticcoind/.crypticcoin
